insert into partita(giornata,risultato,idSquadraOspite,idSquadraCasa) values (1,'0-0',2,3); /* Prima si inserisce una partita vuota, con almeno due utenti, cambiare id squadre appena create*/
insert into punteggio_Giocatore(punteggio,idPartita) values(0,3); /* Poi si vede l'id auto-generato della partita e si crea un punteggio nullo*/
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Mattia','Perin',36,'Juventus','Portiere',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Carlo','Pinsoglio',23,'Juventus','Portiere',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Matthijs','de Ligt',4,'Juventus','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Leonardo','Bonucci',19,'Juventus','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Daniele','Rugani',24,'Juventus','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Giorgio','Chiellini',3,'Juventus','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Alex','Sandro',12,'Juventus','Terzino Sinistro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Luca','Pellegrini',17,'Juventus','Terzino Sinistro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Danilo','',6,'Juventus','Terzino Destro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Juan','Cuadrado',11,'Juventus','Terzino Destro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Mattia','De Sciglio',2,'Juventus','Terzino Destro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Manuel','Locatelli',27,'Juventus','Mediano',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Denis','Zakaria',28,'Juventus','Mediano',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Arthur','',5,'Juventus','Mediano',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Weston','McKennie',14,'Juventus','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Adrien','Rabiot',25,'Juventus','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Marley','Aké',38,'Juventus','Ala sinstra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Federico','Chiesa',22,'Juventus','Ala destra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Federico','Bernardeschi',20,'Juventus','Ala destra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Paulo','Dybala',10,'Juventus','Seconda punta',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Dušan','Vlahović',7,'Juventus','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Álvaro','Morata',9,'Juventus','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Moise','Kean',18,'Juventus','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Kaio','Jorge',21,'Juventus','Punta centrale',2);

insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Ionut','Radu',97,'Inter','Portiere',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Samir','Handanovic',1,'Inter','Portiere',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Alex','Cordaz',21,'Inter','Portiere',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Milan','Skriniar',37,'Inter','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Alessandro','Bastoni',95,'Inter','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Stefan','de Vrij',6,'Inter','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Andrea','Ranocchia',13,'Inter','Difensore centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Federico','Dimarco',32,'Inter','Terzino Sinistro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Aleksandar','Kolarov',11,'Inter','Terzino Sinistro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Matteo','Darmian',36,'Inter','Terzino Destro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Danilo','D"Ambrosio',33,'Inter','Terzino Destro',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Marcelo','Brozovic',77,'Inter','Mediano',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Nicolò','Barella',23,'Inter','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Hakan','Calhanoglu',20,'Inter','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Roberto','Gagliardini',5,'Inter','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Matías','Vecino',8,'Inter','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Arturo','Vidal',22,'Inter','Centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Denzel','Dumfries',2,'Inter','Centrocampista di destra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Robin','Gosens',18,'Inter','Centrocampista di sinistra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Ivan','Perisic',14,'Inter','Centrocampista di sinistra',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Joaquín','Correa',19,'Inter','Seconda punta',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Lautaro','Martínez',10,'Inter','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Edin','Dzeko',9,'Inter','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Alexis','Sánchez',7,'Inter','Punta centrale',2);
insert into Giocatore(nome,cognome,numeroMaglia,squadraReale,ruolo,idPunteggioGiocatore) values ('Felipe','Caicedo',88,'Inter','Punta centrale',2);